[package]
name = "wds"
version = "1.0.0"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

once_cell = "1.16.0"

rand = "0.8.5"
fns = "0.0.7"

dav-server = { version = "0.5.2" }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread", "full"] }
hyper = { version = "0.14.24", features = ["server", "tcp", "http1", "http2"] }

jsonwebtoken = "8.2.0"
http-auth-basic = "0.3.3"
cookie = "0.17.0"
time = "0.3.20"

[dependencies.tauri]
version = "1.2"
features = [ 
    "dialog-open", 
    "dialog-save", 
    "window-set-fullscreen", 
    "path-all", 
    "protocol-all", 
    "shell-open", 
    "window-set-always-on-top", 
    "window-set-cursor-position", 
    "window-set-focus"
]

[build-dependencies]
tauri-build = { version = "1.2", features = [] }


[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
